language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- bash shellcheck.sh
before_script:
- autoreconf -i
notifications:
  email: vinceliu+travisci@gmail.com
  webhooks:
    on_success: change
    on_failure: always
